<?php
// $Id$
/**
 * @file
 * Authcache and dynamic content integration
 */

/**
 * Implementation of hook_menu()
 */
function easy_authcache_ui_menu() {
  $items = array();

  $items['admin/settings/performance/easyauthcache'] = array(
    'title' => 'Easy Authcache settings',
    'description' => "Configure easy authcache settings.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('easy_authcache_ui_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'easy_authcache_ui.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 30,
  );

  return $items;
}

/**
 * Set drupal performance config page as default tab
 * @param $menu
 */
function easy_authcache_ui_menu_alter(&$menu) {
  $menu['admin/settings/performance']['type'] = MENU_NORMAL_ITEM;
  $menu['admin/settings/performance/global'] = $menu['admin/settings/performance'];
  $menu['admin/settings/performance/global']['type'] = MENU_DEFAULT_LOCAL_TASK;
}
