<?php
// $Id$

/**
 * @file
 *
 * Module fix pressflow js issue https://bugs.launchpad.net/pressflow/+bug/529252
 */
 
// FOR PRESSFLOW
/**
 * Add the has_js cookie to the user's JS entry
 */
function easy_authcache_pressflow_init() {
  global $user;
  if ($user->uid > 0) {
    drupal_add_js('document.cookie = "has_js=1; path=/";', 'inline');
  }
}

/**
 * Adds a 'has_js' cookie for only logged-in users
 */
function easy_authcache_pressflow_user($op, &$edit, $account) {
  if ($op == 'logout') {
    setcookie('has_js', '', time() - 3600);
  }
}
